services:
  mysql:
    image: 'mysql:8.0.41'
    container_name: mysql-container
    environment:
      - 'MYSQL_DATABASE=ifg_code_test'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=root'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ifg

  zookeeper:
    image: strimzi/kafka:0.20.1-kafka-2.6.0
    container_name: zookeeper-container
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - ifg

  kafka:
    image: strimzi/kafka:0.20.1-kafka-2.6.0
    container_name: kafka-container
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # after change the host, delete the container first
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-container:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-container:2181
    networks:
      - ifg

  app:
    image: quarkus/ifg-code-test-jvm:latest
    container_name: apps-container
    build: .
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysql-container:3306/ifg_code_test
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=root
      - KAFKA_BOOTSTRAP_SERVERS=kafka-container:9092
    networks:
      - ifg
    depends_on:
      - mysql
      - kafka
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    # to retry run when fail

volumes:
  mysql-data:

# all container should run in the same network
networks:
  ifg:
    driver: bridge